### ISSUE TITLE
[BUG] Lexer structured wrong

### ISSUE THREAD

**Issue by darkdarcool** [TheIoLang/io#10]
Your Lexer is OK, but some things aren't what they are supposed to be.

1. The Lexer shouldn't throw errors

The Lexer just tokenizes things, it doesn't throw errors, no matter how bad the code is. That job is for the parser/interpreter.

2. Token types should not be in the same file

You need a file where you can import them, and most languages have a lot of types of tokens, so it's pretty important

There are a couple others, but these are the 2 big ones

These probably need to be fixed before first release

**Comment by JBYT27** [comment]
Oh, okay!
Tysm for the information! I'll switch the syntax ASAP!

**Comment by JBYT27** [comment]
Heya @darkdarcool, so I've edited the Lexer, Tokens, and Parser a bit, but can you let me know if I've syntaxed it correct?

**Comment by darkdarcool** [comment]
Better, but not perfect.

For comments, you should make it a token, not just skipping the line.

Also you should allow any file extension, this allows more flexibility

**Comment by JBYT27** [comment]
Oh, okay. 

Wait, but if I allow any file extension, then how will the language work? All other languages require a file extension, so...

**Comment by darkdarcool** [comment]
Yes, but it is not _required_

**Comment by darkdarcool** [comment]
I can run a python file with a `.js` extension

**Comment by JBYT27** [comment]
Oh. So what you’re suggesting is that I should leave the file extension as blank?

**Comment by darkdarcool** [comment]
I think that you should take out the file extension checker, it doesn’t make sense you have it

**Comment by JBYT27** [comment]
Oh, okay! Thanks for the suggestion! 

I'll do that ;D

**Comment by JBYT27** [comment]
This issue and #8 are linked

**Comment by darkdarcool** [comment]
also @JBYT27, do you have a discord I can contact you on so I don't have to resort to GitHub?

**Comment by JBYT27** [comment]
Well, I deleted my other account, but I'll make a new one, and I'll tell you the tag ASAP.

**Comment by darkdarcool** [comment]
ok cool

**Comment by JBYT27** [comment]
Hey @darkdarcool, my discord tag is depressedweeb#2189

**Comment by darkdarcool** [comment]
friend req sent
