### ISSUE TITLE
[DOCS] Add contributors here

### ISSUE THREAD

**Issue by kokonut27** [TheIoLang/io#13]

**Comment by JBYT27** [comment]
@all-contributors please add @JBYT27 for code, maintenance, tools, documentation

**Comment by JBYT27** [comment]
@all-contributors please add @JBYT27 for owner

**Comment by JBYT27** [comment]
@all-contributors please add @darkdarcool for code

**Comment by darkdarcool** [comment]
Can you add me to the org so that I can make a couple changes? This seems like a cool project

**Comment by darkdarcool** [comment]
The repl would also be good

**Comment by JBYT27** [comment]
Okay! You got invited, right? (The repo)

**Comment by darkdarcool** [comment]
I accepted the org, and replit works

**Comment by JBYT27** [comment]
Okay! Let me know if you find any bugs or issues!

**Comment by JBYT27** [comment]
Hey @darkdarcool, when can you work on this? Let me know what time works for you, so I can match the time :)

**Comment by darkdarcool** [comment]
I can work on the weekend

**Comment by JBYT27** [comment]
Okay! So is maybe tomorrow or Sunday okay?

**Comment by darkdarcool** [comment]
yup

**Comment by JBYT27** [comment]
Okay! Talk more about this soon ;)

**Comment by JBYT27** [comment]
@all-contributors please add @DillonB07 for design

**Comment by JBYT27** [comment]
@all-contributors please add @DillonB07 for documentation
