### ISSUE TITLE
[QUESTION] Website?

### ISSUE THREAD

**Issue by DillonB07** [TheIoLang/io#17]
Hey,

I don't have any projects I'm currently in the middle of _(other than learning Swift)_, and I noticed that you don't really have a website for this.
Do you want me to make one using Flask?

<details>
<summary>Features</summary>

- Fully responsive with Flexbox
- Working contact form(smtplib)
- Space for documentation
- Interesting design. - If you have a preferred style tell me
- `<code>` blocks syntax highlighting for some languages... _sorry, not this one_
</details>

**Comment by JBYT27** [comment]
Sure! Thanks for the help! I have a quick question though, is it possible for you to maie this in plain HTML, JS, and CSS? If not, flask is okay as well!

**Comment by DillonB07** [comment]
Yes. I could do it in plain HTML, JS and CSS. - I assume you want GH pages?

For the contact form I'll create a repl to handle the emails. _The `form` tag will POST to that repl_

---
Also I really recommend that you sign up for GitHub Student Plan if you have a school email address or evidence of being a student. - https://education.github.com/benefits?type=student

*If it asks you for evidence just take a screenshot whilst being signed in to school email account(with the email visible)*

It's really easy and will definitely benefit you. - You can get 3 months of Replit Hacker for free and a lot more.

**Comment by JBYT27** [comment]
Oh, okay! Sure! Thanks so much!

**Comment by DillonB07** [comment]
No problem

**Comment by DillonB07** [comment]
Sorry, but could you add `the` into the name of the repo? That way the GHP address will be `theiolang.github.io` and not have a `/REPO` on the end.

**Comment by JBYT27** [comment]
Oh, okay! Sorry, and thanks for letting me know!

**Comment by JBYT27** [comment]
Done! Sorry for the problem!
