### ISSUE TITLE
[ENHANCEMENT] Add io logo

### ISSUE THREAD

**Issue by JBYT27** [TheIoLang/io#7]
This language currently is in need of a logo. Please give any feedback for logos!

**Comment by DillonB07** [comment]
![The IO Lang](https://user-images.githubusercontent.com/83948303/145864150-7bea343a-b7af-4e2a-a071-339e4e7205c5.png)

I made this. Not sure if it's what you were looking for?

**Comment by JBYT27** [comment]
Ooh, nice! Nono, I'm okay with any logo personally, as I'm horrible at logo design xD Thanks so much!

**Comment by DillonB07** [comment]
It isn't that hard to make a logo. I'd say that one took about 5-10 minutes. Just find a good tool to use.

**Comment by JBYT27** [comment]
Lol, okay! Thanks!
