### ISSUE TITLE
[ENHANCEMENT] Use PEG

### ISSUE THREAD

**Issue by darkdarcool** [TheIoLang/io#8]
Using PEG will allow you to get the lexer and parser done really quickly, and the _right_ way, and there's less room for error.

I recommend considering this

**Comment by JBYT27** [comment]
Could you give a link? Also, whats the difference between PEG and PLY (or SLY)?

And I'm purposely trying to start the Lexer and Parser on my own for a challenge :)

**Comment by darkdarcool** [comment]
Look at this: https://github.com/erikrose/parsimonious

Also PEG is something you compile via command line, and it omits a file that can be used.

Python uses this for it's lexer and parse(but in C), and it is quite good

**Comment by JBYT27** [comment]
Oh, okay. I'll try that later, in if you don't mind, is it possible if you could set up a PR example? Or a Repo example?

Thanks for the info!

**Comment by darkdarcool** [comment]
I can’t, it’s kind of special to the syntax you have in mind. There is an online version at [https://pegjs.org/](this), but it’s the node version.

**Comment by JBYT27** [comment]
Oh, okay. Thanks!
